[package]
name = "rusty-deser"
version = "1.0.1"
edition = "2021"
description = "High-performance binary deserialization engine with safety-first design."
license = "MIT"
repository = "https://github.com/programerweb1985/rusty-deser"
keywords = ["deserialization", "binary", "parsing", "no-std", "performance"]
categories = ["parsing", "encoding"]

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dev-dependencies]
